name = 3 Col
description = A simple 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = 3col-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[slideshow] = Slideshow
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[bottom_left]    = Bottom Left
regions[bottom_right]   = Bottom Right
regions[footer_left]    = Footer Left
regions[footer_right]   = Footer Right
; Stylesheets
;stylesheets[all][] = css/layouts/3col/3col.layout.css
; JS
;scripts[] = ../../js/jquery.infieldlabel.min.js
;scripts[] = ../../js/infieldlabels.js
;scripts[] = ../../js/dropdown.js
